### ISSUE TITLE
Add a corpus of sources that should be parseable

### ISSUE THREAD

**Issue by robrix** [tree-sitter/tree-sitter-javascript#10]
I’d like if we could provide a bunch of sources that this grammar should parse. I think referencing them by URL/SHA/path (repo/tree/file) would be reasonable so we don’t have to bloat the size of the repo.

We probably don’t need to worry about their specific parse trees (that seems like a job for the existing unit test system), just pass/fail.

**Comment by robrix** [comment]
This might generalize to the other grammars as well.

**Comment by maxbrunsfeld** [comment]
Yeah, I think it'd be good for all the grammars to have this as part of their CI builds. I like the idea of specifying URLs. We should probably make this part of the `tree-sitter` command line tool. Maybe it could output benchmarking information for each file too.

**Comment by maxbrunsfeld** [comment]
We've got a pretty big corpus now; a couple of big JS files checked into the `examples` folder, plus the `npm` repository and all of its dependencies. We can continue to add more examples if we discover some example files that don't parse successfully.
