### ISSUE TITLE
Failing "single-line blocks without semicolons" test

### ISSUE THREAD

**Issue by joshvera** [tree-sitter/tree-sitter-javascript#12]
The `single-line blocks without semicolons` test is failing on master with:

```
 single-line blocks without semicolons 
        »        
        actual expected 
         
        (program (expression_statement (function (identifier) (statement_block (ERRORtrailing_expression_statement (identifier)))))) (UNEXPECTED '}'))))) (expression_statement (function (identifier) (statement_block (ERRORtrailing_return_statement (identifier) (UNEXPECTED '}')))))))))))) 
```

Steps to Reproduce:
1. Run `npm test`

**Comment by maxbrunsfeld** [comment]
I can't reproduce this on a clean install. Have you recompiled the native code with the recent changes on master?

**Comment by maxbrunsfeld** [comment]
Alternatively, the way that I usually iterate on these grammars is to install `node-gyp` globally (`npm install --global node-gyp`). That's the module that `npm` uses to build native dependencies. That way you can recompile `parser.c` without having to run a full `npm install`, which is a bit slow.

**Comment by maxbrunsfeld** [comment]
I need to fix the CI build. I guess something about Travis's infrastructure changed, and you can no longer upgrade clang the way that I used to do it.

**Comment by joshvera** [comment]
@maxbrunsfeld Looks like something was up with my install. `node-gyp build` seems to work 😅
