### ISSUE TITLE
JSDoc comment syntax should be recognized

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter-javascript#126]
As pointed out by @Alhadis in https://github.com/github/semantic/issues/441, the `comment` rule here could perhaps include syntax for recognizing JSDoc syntax, e.g. `@param`.

**Comment by maxbrunsfeld** [comment]
Thanks for the head up! We're handling JSDoc highlighting via a separate grammar - http://github.com/tree-sitter/tree-sitter-jsdoc.
