### ISSUE TITLE
Integration questions

### ISSUE THREAD

**Issue by tim-lebedkov** [tree-sitter/tree-sitter-javascript#133]
Hello,

I would like to parse JavaScript into a syntactic tree in Delphi. 

As far as I understand, I would need a 64 bit .DLL for tree-sitter and another one for tree-sitter-javascript. Where are these DLLs? 

Where are (preferably C) definitions for the DLL functions I would need?

**Comment by Elvares** [comment]
Could you answer me for the question?  What's about delphi?

**Comment by amaanq** [comment]
Hey, you may compile libtree-sitter by just invoking make in the upstream `tree-sitter` library. In here, you just need to compile src/{parser.c, scanner.c} and only need to concern yourself with the exported function `tree_sitter_javascript`. I know this is quite old but hopefully this helps you or anyone else with a similar question.
