### ISSUE TITLE
Add support for optional chaining "?."

### ISSUE THREAD

**Issue by mjambon** [tree-sitter/tree-sitter-javascript#134]
The feature is already being widely used in typescript, in about 10% of the files according to my rough stats. See the related ticket in the tree-sitter-typescript repo: https://github.com/tree-sitter/tree-sitter-typescript/issues/80

I'm thinking of adding the feature to the javascript grammar rather than only adding it to the typescript grammar. Let me know if there's something wrong with the approach. I'll use this reference document: https://tc39.es/ecma262/#sec-optional-chains

**Comment by maxbrunsfeld** [comment]
👍  I agree; we should add this to the JavaScript grammar.

**Comment by mjambon** [comment]
Do you have guidelines for grammar maintenance? Some rules are hidden and some are not. Some rules use the name found in the reference documents (ES6 from 2015 or ES 2021) while some others seem to be workarounds to facilitate parsing or something. For example, the [rule `augmented_assignment_expression` coexists with `assignment_expression`](https://github.com/tree-sitter/tree-sitter-javascript/blob/a2e3d72f82716a20982ecc06c349c54ec40d54df/grammar.js#L694-L710) in `grammar.js` but only the latter occurs in the ecmascript spec. I'd love to throw away any rule that doesn't appear in the spec and replace it by a literal implementation of the spec... but I also expect this approach to fail. I'd be inclined to leave comments explaining any apparent or actual deviation from the spec but I don't see any. Maybe comments aren't that useful for this type of code, I don't know.

Are there conventions, tools, documents that I should be aware of? Generally speaking, do you have tips on how to modify grammars to as to bring them up to date? Does it work best to proceed incrementally or should I not worry too much, add or modify all the rules I want, and only then start testing?

**Comment by maxbrunsfeld** [comment]
Keeping a 1:1 correspondence with the language spec isn’t a goal, because that wouldn’t produce a useful CST. There’s some discussion of this in the docs, but we don’t have a formal system that indicates how things should be structured.

In this case, I think we want to add a new expression rule. You might want to run a widely used JS parser to see what name they use for this “foo.?bar” syntax.

**Comment by mjambon** [comment]
Thank you Max, I'll try something like this.

**Comment by maxbrunsfeld** [comment]
After scanning [the docs on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining), my suggestion would be to add *three* new rules:
* `optional_member_expression`
* `optional_call_expression`
* `optional_subscript_expression`

These would be parallel with the existing `member`/`call`/`subscript` expression rules, and they would match `foo?.bar`, `foo?.(bar)` and `foo?.[bar]` respectively.

I haven't looked into it deeply, so I may be missing something, but that might be a good starting point, which is consistent with the existing style.
