### ISSUE TITLE
Wrong highlighting of jsx components.

### ISSUE THREAD

**Issue by luisiacc** [tree-sitter/tree-sitter-javascript#161]
Hy, so there was an issue a little while ago where on react files, normal tags (such as `<br />`, `<div />`, etc...) where not highlighted as TSTag but as TSVariable, well that is now done correctly, but now custom components(Ex: `<Home />`) are not highlighted as TSTag but as TSType, so that should be fixed since they should be highlighted as TSTag.

**Comment by maxbrunsfeld** [comment]
That configuration is part of either neovim or nvim-treesitter. For issues like this, that happen in neovim, please open an issue on one of those repos.
