### ISSUE TITLE
Jxs props should be a different group

### ISSUE THREAD

**Issue by luisiacc** [tree-sitter/tree-sitter-javascript#162]
Right now on jsx files, components props are been highlighted as TSProperty, I think they should be a separate group for more customizable themes.
![image](https://user-images.githubusercontent.com/31720261/111093977-99214f00-8510-11eb-872e-9458c14080ae.png)

**Comment by maxbrunsfeld** [comment]
Closing this out because I think it's an issue with Neovim or nvim-treesitter. Feel free to open an issue on one of those repos.
