### ISSUE TITLE
support for lit-element

### ISSUE THREAD

**Issue by tamis-laan** [tree-sitter/tree-sitter-javascript#163]
It would be nice to have syntax highlighting support for lit-element. Now your just starting at a mono colored screen.

**Comment by patrickt** [comment]
Hi there 👋🏻 Can you clarify your request a little? I’m not sure what you mean by lit-element. As regards syntax highlighting, usually issues like that are the responsibility of your text editor’s tree-sitter integration.

**Comment by tamis-laan** [comment]
Ah sorry I have found out that I did not have the tree sitter html package installed, no html tagged template literals are interpreted by treesitter as html and are syntax highlighted appropriately.
