### ISSUE TITLE
Parser not adding TSParameter to parameters

### ISSUE THREAD

**Issue by dansdantas** [tree-sitter/tree-sitter-javascript#169]
Don't know if i'm at the right place, but, for some reason, on javascript files, parser does not add `TSParameter` to so it can properly be highlighted.

Minimal (neo)vimrc:
```vim
set runtimepath+=$HOME/.config/nvim/plugged/nvim-treesitter
set runtimepath+=$HOME/.config/nvim/plugged/oceanic-next
set runtimepath+=$HOME/.config/nvim/plugged/playground
set statusline=%{nvim_treesitter#statusline(120)}

lua <<EOF
  local treesitter = require'nvim-treesitter.configs'
  treesitter.setup {
    ensure_installed = "all",
    highlight = { enable = true },
  }
EOF

set termguicolors
set background=dark
syntax enable
colorscheme OceanicNext
```

Neovim nightly:
![image](https://user-images.githubusercontent.com/3410485/114960530-9b433a00-9e3d-11eb-9cdc-d284d582a038.png)

On playground looks like it was correctly detected, so i'm not sure what could be happening. Or even if it should add that highlight class.

**Comment by mjambon** [comment]
Looks like a neovim question. I would try there: https://github.com/neovim/neovim/issues
