### ISSUE TITLE
Semicolons following for statements are not parsed

### ISSUE THREAD

**Issue by robrix** [tree-sitter/tree-sitter-javascript#17]
This parses:

```js
for (var i = 0; i < 10; i++) { console.log(i); }
```

But this does not:

```js
for (var i = 0; i < 10; i++) { console.log(i); };
```

**Comment by maxbrunsfeld** [comment]
Ah man, forgot about empty statements. I think this is fixed by https://github.com/tree-sitter/tree-sitter-javascript/commit/d52d12abeb9d0cd4d2ce21a4da53abd61d3cdecd.

**Comment by joshvera** [comment]
@maxbrunsfeld should we go back and delete [`terminator()`](https://github.com/tree-sitter/tree-sitter-javascript/commit/d52d12abeb9d0cd4d2ce21a4da53abd61d3cdecd#diff-95fc33185b7215010b60f43469000a7aL189) parsers from the various statements?

**Comment by maxbrunsfeld** [comment]
I think those are still needed. This change just allows redundant semicolons basically.
