### ISSUE TITLE
Incorrect parse error on destructuring assignment

### ISSUE THREAD

**Issue by sguillia** [tree-sitter/tree-sitter-javascript#185]
* The following piece of code is valid but it is parsed incorrectly:

```javascript
const { hooks: { hashPassword } = {} } = {}
```

* Here's a link to the TypeScript Playground showing that the snippet above is valid JavaScript or TypeScript:

https://www.typescriptlang.org/play?#code/MYewdgzgLgBA3jAFiEBrCAueSCGFEAKeEA7iAE4AmMAvjALzx12Nw0BQQA
The code does not pass the Typescript type checking

* The output of `tree-sitter parse` is the following:

```
tree-sitter parse ./code.js
(program [0, 0] - [1, 0]
  (lexical_declaration [0, 0] - [0, 36]
    (variable_declarator [0, 6] - [0, 36]
      name: (object_pattern [0, 6] - [0, 31]
        (pair_pattern [0, 8] - [0, 31]
          key: (property_identifier [0, 8] - [0, 13])
          value: (object_pattern [0, 15] - [0, 31]
            (shorthand_property_identifier_pattern [0, 17] - [0, 29]))))
      value: (object [0, 34] - [0, 36])))
  (ERROR [0, 37] - [0, 40])
  (statement_block [0, 41] - [0, 43]))
./code.js	0 ms	(MISSING "}" [0, 31] - [0, 31])
```

* Notes

With grammar 0.16.0, used to work fine.

* Minimal reproducible example

https://github.com/sguillia/tree-sitter-javascript-regression

**Comment by mjambon** [comment]
Thanks for reporting this bug! Here's the same thing in compact form:
```js
const { k: x = 0 } = {}
```
It's semantically equivalent to `const x = 0`.

[[typescript playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBA3jA1gLhgDxgXhgBhgXy3nwChRIQAbAUwDpKQBzACjQEoBuEoA)]

Here we see that the parser doesn't know what to do with the default value specification (`= 0`):
![image](https://user-images.githubusercontent.com/343265/125379758-f229b400-e345-11eb-99a7-7ffe28b62112.png)

**Comment by FnControlOption** [comment]
I had a go at fixing this and I'm close to opening a pull request, but I have a question:

```js
let { x: y = 1 } = { x: 2 } // result: y = 2
// How should the fields here be named?
```

```js
let { x: y } = { x: 2 } // result: y = 2
// Here, `x: y` matches pair_pattern
// x is 'key' field, and y is 'value' field
```

```js
let { x = 1 } = { x: 2 } // result: x = 2
// Here, `x = 1` matches object_assignment_pattern
// x is 'left' field, and 1 is 'right' field

// Equivalent to:
let { x: x = 1 } = { x: 2 }
```
