### ISSUE TITLE
Incomplete variable declaration before return statement causes incorrect tree linkage (node is own uncle)

### ISSUE THREAD

**Issue by gushogg-blake** [tree-sitter/tree-sitter-javascript#186]
With the following code, I'm seeing a zero-length node of type `;` that is its own parent's parent's next sibling:

```javascript
function a() {
    let
    return {}
}
```

I ran into an infinite loop when trying to traverse this tree.  After processing an `identifier` node for the `return` keyword, it doesn't have a `nextSibling` so we go to its parent which is a `variable_declarator`.  The next sibling of the `variable_declarator` is the zero-length semicolon node, so that's the next logical node to process.  After processing that node, it doesn't have a next sibling so we go to its parent, which is the original `identifier`.  There are other inconsistencies associated with this, e.g. the `identifier` node has a `childCount` of 0 even though it has nodes that point to it via `parent`.

**Comment by amaanq** [comment]
It'd be nice if you can check if this is still an issue (there's been a plethora of changes here and in tree-sitter core), if it is then I'd like to investigate it more - thanks!
