### ISSUE TITLE
Incorrect tree structure with coment starting in same line as closing bracket of a function

### ISSUE THREAD

**Issue by marcosboggia** [tree-sitter/tree-sitter-javascript#188]
The following piece of code is valid but it is parsed incorrectly:

```javascript
class Docstring {
 
    /** DOCSTRING */
    foo1() {
      return;
     }         /*** WEIRD
     
     DOCSTRING
     ***/
    foo2() {
      return;
    }
}
```

Here's a link to the TypeScript Playground showing that the snippet above is valid JavaScript or TypeScript:

https://www.typescriptlang.org/play?filetype=js#code/MYGwhgzhAEAiD2wIBcBOBLAdgc2gbwChojpSB6AKgrgHkBhAZQBUAlASQDkBxaCsk0gDN48AIwAKAJT4BpaKgCmyAK6pMAblnQAvnL3kq1AOoBRNi1hatses3bcth-nuHwATFJn75S1RtnaBNpAA

The output of tree-sitter parsing is the following(using playground website: https://tree-sitter.github.io/tree-sitter/playground):
![Screenshot from 2021-08-11 16-30-24](https://user-images.githubusercontent.com/18308502/129091644-e7ce5e0e-c02c-420e-af62-3e579a864f37.png)

I've found an incorrect tree structure when there is a comment in the same line of a closing bracket from a function body.
As we can see, tree-sitter finds the "weird comment" inside the body of foo1 function even though this comment is written after the closing bracket of the body function. A semicolon or writting the comment below would fix the issue, but still this corner case could happen eventually since not everybody uses semicolon or maybe a misplaced line break accidentally falls in that place and breaks the tree structure.
Thanks!

**Comment by maxbrunsfeld** [comment]
Thanks for the report! I think this may have to do with our automatic semicolon insertion logic in the external scanner.

**Comment by guillaumebrunerie** [comment]
I think this is actually due to the fix in https://github.com/tree-sitter/tree-sitter-javascript/pull/104 which (as a workaround) allowed automatic semicolons at the end of statement blocks, and that automatic semicolon ends up eating the whole comment.
I tried with the initial commit of #104 which used a different token for empty statement blocks (instead of allowing automatic semicolons after statement blocks), and it works as it should.
