### ISSUE TITLE
Function expressions are wrongly supported inside expression_statement

### ISSUE THREAD

**Issue by NotWearingPants** [tree-sitter/tree-sitter-javascript#205]
The following piece of code is invalid but it is parsed correctly:

```javascript
function(){}
```

[Here's a link to the TypeScript Playground showing that the snippet above is invalid JavaScript or TypeScript](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mAFASgN4F8g)

The output of `tree-sitter` playground is the following:

```
program [0, 0] - [1, 0]
  expression_statement [0, 0] - [0, 12]
    function [0, 0] - [0, 12]
      parameters: formal_parameters [0, 8] - [0, 10]
      body: statement_block [0, 10] - [0, 12]
```

A statement that start's with `function` is always a function declaration, it can't be a function expression inside an expression statement.
Parenthesizing the function expression is valid, and parses correctly, but the snippet above should result in a `function_declaration` with an ERROR.

This is a very common mistake in JavaScript, so it is important that editors that use tree-sitter flag this as an error and show what the problem is.

**Comment by maxbrunsfeld** [comment]
See https://github.com/tree-sitter/tree-sitter-javascript/issues/206#issuecomment-930616944

Again, there would be no benefit in failing to parse this code; this can be considered a semantic error.
