### ISSUE TITLE
** operator should be right associative

### ISSUE THREAD

**Issue by captbaritone** [tree-sitter/tree-sitter-javascript#210]
The following piece of code is valid but it is parsed incorrectly:

```javascript
1 ** foo ** 2
```

Here's a link to the TypeScript Playground showing that the snippet above is valid JavaScript or TypeScript:

https://www.typescriptlang.org/play?#code/IwAgVGIGYPY+kBMAoIA

The output of `tree-sitter parse` is the following:

```
(program [0, 0] - [1, 0]
  (expression_statement [0, 0] - [0, 13]
    (binary_expression [0, 0] - [0, 13]
      left: (binary_expression [0, 0] - [0, 8]
        left: (number [0, 0] - [0, 1])
        right: (identifier [0, 5] - [0, 8]))
      right: (number [0, 12] - [0, 13]))))
```

This should be parsed as a binary expression with a number on the left hand side and another binary expression on the right hand side. Instead we get a binary expression on the right hand side, and a number on the right hand side. ie, we get `(1 ** foo) ** 2` but we should get `1 ** (foo ** 2)`.

[According to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence):

> [...] Exponentiation, on the other hand, is right-associative, so 2 ** 3 ** 2 is the same as 2 ** (3 ** 2).

I've also compared this with Babel's parse of that expression. Babel gives the expected `1 ** (foo ** 2)` parse.

The relevant code in this repo is [here](https://github.com/tree-sitter/tree-sitter-javascript/blob/fdeb68ac8d2bd5a78b943528bb68ceda3aade2eb/grammar.js#L826) where we unconditionally treat all binary expressions as left associative. 

Motivating context: https://twitter.com/captbaritone/status/1465462792467595265

**Comment by mjambon** [comment]
thanks for the report!
