### ISSUE TITLE
nashorn extension syntax support

### ISSUE THREAD

**Issue by kran** [tree-sitter/tree-sitter-javascript#228]
nashorn is a jvm based js runtime, and some syntax extensions implemented by it. 

eg: <<EOF  string block, for each loop
these syntax broken the highlight and indent in nvim.

link: https://wiki.openjdk.org/display/Nashorn/Nashorn+extensions

**Comment by amaanq** [comment]
This isn't in base javascript though, you can create your own grammar to extend this one and add that feature.
