### ISSUE TITLE
Ignored values in destructuring assignments are not reflected in generated AST.

### ISSUE THREAD

**Issue by ypaliy-vdoo** [tree-sitter/tree-sitter-javascript#230]
The following piece of code is valid but it is parsed incorrectly:

```javascript
const [a, , b] = [0, 1, 2, 3, 4];
```

Here's a link to the TypeScript Playground showing that the snippet above is valid JavaScript or TypeScript:

https://www.typescriptlang.org/play?#code/MYewdgzgLgBA2gQwDQxQIwLowLzwAwoCMKATCgMwoAsGA3ALABQokIANgKYB0bIA5gApkMNAEpaQA

The output of `tree-sitter parse` is the following:

```
(program [0, 0] - [1, 0]
  (lexical_declaration [0, 0] - [0, 33]
    (variable_declarator [0, 6] - [0, 32]
      name: (array_pattern [0, 6] - [0, 14]
        (identifier [0, 7] - [0, 8])
        (identifier [0, 12] - [0, 13]))
      value: (array [0, 17] - [0, 32]
        (number [0, 18] - [0, 19])
        (number [0, 21] - [0, 22])
        (number [0, 24] - [0, 25])
        (number [0, 27] - [0, 28])
        (number [0, 30] - [0, 31])))))
```

Explain what you were expecting:
I would expect an indication that an element is skipped.

Feature documentation:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment 
Ignoring some returned values

**Comment by amaanq** [comment]
I'm not sure what you're expecting here, parsing whitespace as tokens in a conditional manner would be tricky, and imo this is not tree-sitter's job to show you an element being skipped
