### ISSUE TITLE
Support for 'export * as ns from ...'

### ISSUE THREAD

**Issue by hyrious** [tree-sitter/tree-sitter-javascript#231]
I found this when I see code rendered as follows:

JavaScript ('as' wrong color):
```js
export * as bar from 'bar'
```

TypeScript:
```ts
export * as bar from 'bar'
```

I'm not sure whether github uses tree-sitter to highlight its code blocks, but the behavior seems to match. Reviewing the grammar.json also tells me it is not supported yet.

**Comment by mjambon** [comment]
Parsing works on the example you provided:
```
$ tree-sitter parse <(echo "export * as bar from 'bar'")
(program [0, 0] - [1, 0]
  (export_statement [0, 0] - [0, 26]
    (namespace_export [0, 7] - [0, 15]
      (identifier [0, 12] - [0, 15]))
    source: (string [0, 21] - [0, 26]
      (string_fragment [0, 22] - [0, 25]))))
```

However, I don't know how highlighting works in tree-sitter or whether Github uses tree-sitter for this. Sorry!

**Comment by hyrious** [comment]
Yes you're right, I saw the grammar there.

It was just the playground (https://tree-sitter.github.io/tree-sitter/playground) does not updated.
