### ISSUE TITLE
Comment not recognized in the middle of a ternary expression

### ISSUE THREAD

**Issue by savetheclocktower** [tree-sitter/tree-sitter-javascript#255]
This is a regression that was somehow introduced in e3a5149. This snippet parses correctly on its parent commit (2cc5803), but has been broken ever since.

The following piece of code is valid but it is parsed incorrectly, omitting the expected `comment` node:

```javascript
let foo = bar
  // this is a comment
  ? 'baz' : 'thud';
```

Here's a link to the TypeScript Playground showing that the snippet above is valid JavaScript or TypeScript:

https://www.typescriptlang.org/play?ssl=3&ssc=1&pln=3&pc=20#code/DYUwLgBAZg9jEF4JgE4FcQCgCQB6XyAFgJYDOEZEAhhAMYwC2DIAdmJhBAPwQDkARlQBevCAC4+YQmgAmvANxA

The output of `tree-sitter parse` is the following:

```
(program [0, 0] - [2, 19]
  (lexical_declaration [0, 0] - [2, 19]
    (variable_declarator [0, 4] - [2, 18]
      name: (identifier [0, 4] - [0, 7])
      value: (ternary_expression [0, 10] - [2, 18]
        condition: (identifier [0, 10] - [0, 13])
        consequence: (string [2, 4] - [2, 9]
          (string_fragment [2, 5] - [2, 8]))
        alternative: (string [2, 12] - [2, 18]
          (string_fragment [2, 13] - [2, 17]))))))
```

**Comment by amaanq** [comment]
Interesting - I think a solution would be to scan comments w/ the external scanner too
