### ISSUE TITLE
method_definition not producing generator_function children

### ISSUE THREAD

**Issue by raczosala** [tree-sitter/tree-sitter-javascript#256]
The following piece of code is valid but it is parsed incorrectly:

```javascript
var obj = { *foo() { yield 0; } };
```

Here's a link to the TypeScript Playground showing that the snippet above is valid JavaScript or TypeScript:

https://www.typescriptlang.org/play?#code/G4QwTgBA9gRgVhAvBA3hAVAMylAFASlQgE8BLAUwBsATCABgG4IBfFhoA

The output of `tree-sitter parse` is the following:

```
(program [0, 0] - [0, 34]
  (variable_declaration [0, 0] - [0, 34]
    (variable_declarator [0, 4] - [0, 33]
      name: (identifier [0, 4] - [0, 7])
      value: (object [0, 10] - [0, 33]
        (method_definition [0, 12] - [0, 31]
          name: (property_identifier [0, 13] - [0, 16])
          parameters: (formal_parameters [0, 16] - [0, 18])
          body: (statement_block [0, 19] - [0, 31]
            (expression_statement [0, 21] - [0, 29]
              (yield_expression [0, 21] - [0, 28]
                (number [0, 27] - [0, 28])))))))))
```

I believe the generator function should be part of the AST

**Comment by amaanq** [comment]
well the asterisk is parsed correctly, it is a method definition after all and the asterisk is accounted for

**Comment by raczosala** [comment]
it is indeed account for, I guess if this is the intended behavior then this can be closed.

then the only way to capture generator functions would be by using an unnamed node `(method_definition "*")`

**Comment by amaanq** [comment]
yep you can capture it like that
