### ISSUE TITLE
Bunch of errors caused by `e.innerHTML` in userscript

### ISSUE THREAD

**Issue by johannesrld** [tree-sitter/tree-sitter-javascript#265]
The following piece of code is valid but it is parsed incorrectly:

```javascript
(function() {
  window.addEventListener("load", (_) => {
    Array.prototype.slice
      .apply(document.querySelectorAll("div.usertext-body a"))
      .filter(a => a.innerText === "<image>").forEach(e => {
        e.innerHTML = "<img style=\"max-height: 45vh;\"/>";
        e.parentElement.querySelectorAll("span.res-freetext-expando").forEach(e =>
          e.remove()
        );
        e.lastElementChild.src = e.href;
      });
  });
})();
```

Here's a link to the TypeScript Playground showing that the snippet above is valid JavaScript or TypeScript:

[Typescript Playground link](https://www.typescriptlang.org/play?ssl=14&ssc=1&pln=1&pc=1#code/BQMwrgdgxgLglgewsAlAAgN4Cg1oO5wQAmCeAdAIZFECiAbgKYQwAycAzjEwwE7ABEAGwRV+AGjTAA+ugC8APkw5caAII8eFAJ5kADjwQxDW3QzLtBcKA2Uq0lXbsFbgJKGAC2TGGQCOYXi0AZQZBBlgEHlVBQQEiODoyMHZeLgAPGABaACMEIi00Cn4UFFsVMhA4QS4+CjQFQrJCCF4AFQYM+tlZNH4AHjgPCgBzBnliisiaCigAC2AGesVsOzszZt4ACVaAWRZ63oGPYbROLTDZAB1+IbTM2YY4YdmYAC40ABYAVjpZgG5rgB6cZ-MprPQUHjeGhhLzMPwBHjBULhIxRGICdi6CgQMhQ9iZEBQhjpLIdbHEBATEBTGbzRYKMGrMxQjwIRioJm4FCg1YqMyCCicGEMOEwADCsyqRHMPCgBzMsyhIF5qwAvjzlBrQRrUKCgA)

The output of `tree-sitter parse` is the following:
Installing tree-sitter and the parser was incredible inscrutable so i gave up trying to run the parse command, although neovims `InspectTree` Command might be the same thing, in which case there are a bunch of `(ERROR)` statements all throughout the tree, even in places arent anywhere near the offending line.

**Comment by amaanq** [comment]
Nope, neovim's `InspectTree` is not the same, as they use injections to improve parse output but which can be the cause of ERROR nodes. And even with neovim, I don't see any errors in `InspectTree`.

You can just install tree-sitter cli with `cargo install tree-sitter`, but again there is no parse error.
