### ISSUE TITLE
Consider "un-aliasing" function named-node kind vs function token kind?

### ISSUE THREAD

**Issue by helixbass** [tree-sitter/tree-sitter-javascript#268]
This isn't a bug I suppose but given that at least in the Rust `tree-sitter` bindings `Node::kind()` returns the "token value" for non-named nodes, there is a bit of a "namespace conflict" where actual `(function)` named nodes report their kind as `"function"` but then the non-named nodes for the `function` keyword (in function expressions/declarations) also reports its kind as `"function"`

So were one doing it from scratch, I'd probably suggest using eg `(function_expression)` instead of `(function)`

But I'm guessing "breaking" grammar changes should be minimized?

So I don't know if eg aliasing the `function` keyword token (`alias('function', 'function_keyword')`) would be less likely to break existing code?

The current situation should be work-around-able in most if not all situations, but it just "bit me" so figured I would raise the concern

Perhaps there is a deeper question there of whether named-node kinds should be sharing the same "namespace" as non-named-node kinds (at the Rust API level or wherever)?

**Comment by helixbass** [comment]
(same thing with `(class)` vs `class` keyword node)

**Comment by amaanq** [comment]
i see what you mean - it can be a bit confusing. what about `function_definition`

**Comment by helixbass** [comment]
> what about `function_definition`

As a renaming idea for `(function)` -> `(function_definition)`? Ya that also seems reasonable. My suggestion of `(function_expression)` comes from the names I've seen used by JS/Typescript AST's, which arguably differentiates "function expression" vs "function declaration" a bit more clearly

**Comment by amaanq** [comment]
Can you link to where you saw those ASTs? More official = more better :wink:

**Comment by helixbass** [comment]
Sure here are a couple astexplorer.net links:

[Babel AST](https://astexplorer.net/#/gist/cfef01bf2e2b57b31bcaeff4a1f67ca5/3c2c97d7a10d4bf84627b459e7cf310bec22f4e0)
[ESLint (espree) AST](https://astexplorer.net/#/gist/cfef01bf2e2b57b31bcaeff4a1f67ca5/29eeed24fdd1d20eeeee59eacb0316a12a7b5af9)
[Typescript AST](https://astexplorer.net/#/gist/cfef01bf2e2b57b31bcaeff4a1f67ca5/bba916f0175bf6ce08f0cf19742783b91fd03ce5)
