### ISSUE TITLE
Compiling parser as shared library

### ISSUE THREAD

**Issue by diasbruno** [tree-sitter/tree-sitter-javascript#271]
In many tree-sitter projects, they have a `Makefile` to build the libraries to be used with C (I'm currently using bindings for Common Lisp).

Copying the makefile from other projects seems to work (probably it should be good if every tree-sitter repository follows the same structure).

Is the Makefile missing or some repositories uses a different build mechanism?

**Comment by amaanq** [comment]
there's a makefile now
