### ISSUE TITLE
`tree-sitter-javascript` version 0.21.2 does not compile on Windows

### ISSUE THREAD

**Issue by Luni-4** [tree-sitter/tree-sitter-javascript#321]
This commit https://github.com/tree-sitter/tree-sitter-javascript/commit/4928d3d18019a848906855476fde2dc8be030217 fixes the problem. Is it possible to release a `0.21.3` version? Thanks in advance!

**Comment by amaanq** [comment]
sure

**Comment by amaanq** [comment]
npm, pypi, and crates have 0.21.3 now with this fix

**Comment by Luni-4** [comment]
Thanks a lot!
