### ISSUE TITLE
tagged template literal parsing issues

### ISSUE THREAD

**Issue by mohamedmansour** [tree-sitter/tree-sitter-javascript#343]
The following piece of code is valid but it is parsed incorrectly:

```javascript
export const styles = css`:host {}`.withBehaviors(css` :host {}`);
```

Here's a link to the TypeScript Playground showing that the snippet above is valid JavaScript or TypeScript:

https://www.typescriptlang.org/play/?ssl=32&ssc=1&pln=28&pc=1#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVzQZ3wAp8YpMUBzfALjgBVgBbMAGwEMZgBlMi6gIJQo7AJ4AaOADoZAN3askwWnHYpRAbQC6ASjoBRVs2AoYvUUfxwA3gCg4DuFGAwkUXCmAB3OIeOnzSxI+KnxJeUVlHQBuWwBfW1tQSFg8DkJfIyYTMxgLZRt7RzByeS44UnyVUnIqWKKHNBwapAxoYNrqOkYWDi5eTvwhEQk4CKUVNU1dQsc5uBgAC0x8KUrLOABeCpDqKQArCAoiAHITnTgAajGFCYOjlFPz2LmEhrgvTCWAIWBF9lk2CgxBkUgARn8AUCVAAxaBoYAAEwAwhBWNB8IFlItgC5fv9AdBtHoFssrHZ5o5nK53KSVi9HAk3sloPA0OkrHCoAiUWiMVj8Di8ZDCVBZsVSpxgDsqgYsjkBfU5k0UC02lBgrLMv5clULhTKXTVusCtsTfgGQ4mYkVaREPCkaj0cCBUKYPiodAtnBNZY5TqBSSuTynfy8pY3R7RVsAHzihzUtwebxwYOOvku8PY3HukVA31RWJxeos1K2+Dm70EfAAAxoiwgduscRrUk+PzzGKI7wQDt5zsxWcFOaj+erdYbTZbOlsMUSQA

The output of `tree-sitter parse` is the following:

```
program [0, 0] - [1, 0]
  export_statement [0, 0] - [0, 66]
    declaration: lexical_declaration [0, 7] - [0, 66]
      variable_declarator [0, 13] - [0, 65]
        name: identifier [0, 13] - [0, 19]
        value: call_expression [0, 22] - [0, 65]
          function: member_expression [0, 22] - [0, 49]
            object: call_expression [0, 22] - [0, 35]
              function: identifier [0, 22] - [0, 25]
              arguments: template_string [0, 25] - [0, 35]
                string_fragment [0, 26] - [0, 34]
            property: property_identifier [0, 36] - [0, 49]
          arguments: arguments [0, 49] - [0, 65]
            call_expression [0, 50] - [0, 64]
              function: identifier [0, 50] - [0, 53]
              arguments: template_string [0, 53] - [0, 64]
                string_fragment [0, 54] - [0, 63]
```

The `withBehaviors` is being treated as a `property_identifier` instead of a `call_expression`,  `css` is basically a template tagged literal which can return anything, and `withBehavior` is in my case a function, and in a different level in the node.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by amaanq** [comment]
:thinking: I would think this is correct, you have a call expression that wraps a member expression, `foo.bar()` has a similar parse tree which makes sense, you're calling a function where the function is the member `bar` of `foo` is how I see it

**Comment by mohamedmansour** [comment]
But shouldn't the arguments be part of withBehavior and not the first css template literal? Since withBehavior is a function. Right now it is thinking the last css template literal is the arguments of the first one which is not true

**Comment by jackschu** [comment]
This looks correct as is. Totally agree with amaanq here. It also lines up with how ESTree (and therefore many other parsers) handle this. 

eg https://github.com/estree/estree/blob/030f54587973c1deeeb9554339f1f7e0ca3b7e4b/es2015.md#expressions
says a call expression is made up of `callee` which is another  expression. For tree-sitter-javascript this is called `function` rather than `callee` and in this example it is a member_expression  (accessing the member named `withBehaviors`)

**Comment by mohamedmansour** [comment]
Thank you!
