### ISSUE TITLE
Line separator support

### ISSUE THREAD

**Issue by Arcanemagus** [tree-sitter/tree-sitter-javascript#70]
JavaScript, for some reason, allows the ` `/`\u2028` (Line separator) character to delineate new lines in source code.

`tree-sitter-javascript` should support this and allow Atom to interpret those characters as a new line, much as `\n` or `\r\n` are handled currently.

Related issues:
https://github.com/tree-sitter/tree-sitter/issues/105
https://github.com/AtomLinter/linter-eslint/issues/746

**Comment by maxbrunsfeld** [comment]
On the parsing side, I think all we need to do is 
* Include `\u2028` in the grammar's `extras`
* Treat `\u2028` like we treat `\n` in the external scanner, for the purposes of automatic semicolon insertion.

**Comment by Arcanemagus** [comment]
Oh wow, just did a bit further digging and apparently `\u2029` (Paragraph separator) is also allowed, I have no idea what they were thinking there.

In any case, from the way you wrote that it seems that parsing into the syntax tree with those symbols will be "simple", is there more that would be needed for this to be handled in Atom to allow the APIs already in place to handle it properly? (eg. how you can grab text without the line endings)

**Comment by maxbrunsfeld** [comment]
Oops didn’t mean to close this. Treating those characters as line endings in Atom is a completely separate issue. I doubt we will ever do it since it is such an edge case.
