### ISSUE TITLE
Add escape sequences within string literals and regex components to JS grammar

### ISSUE THREAD

**Issue by queerviolet** [tree-sitter/tree-sitter-javascript#79]
This will be helpful for syntax highlighting. Also, escape sequences and regex operations are semantic parts of JS that should make it into the tree.

**Comment by maxbrunsfeld** [comment]
Escape sequences [were added](https://github.com/tree-sitter/tree-sitter-javascript/commit/9a3c911fc67ce8e85e4d5386e762c6a073484fb2), and we're going to handle regexes using [tree-sitter-regex](https://github.com/tree-sitter/tree-sitter-regex).
