### ISSUE TITLE
for await...of statement prevents function from being folded properly

### ISSUE THREAD

**Issue by aviflax** [tree-sitter/tree-sitter-javascript#85]
My code unfolded:

```js
async function readEntireTextStream(stream) {
  let str = '';
  stream.setEncoding('utf8');
  for await (const chunk of stream) {
    str += chunk;
  }
  return str;
}
```

What it looks like when I try to fold the function:

<img width="470" alt="screen shot 2018-11-01 at 16 14 35" src="https://user-images.githubusercontent.com/141844/47877045-4f2ce800-ddf1-11e8-8077-f080a2b2055d.png">

I’ve included the following function just to illustrate how I expect `readEntireTextStream` to fold: exactly like `puppeteerOpts`.

I know `for await...of` is only a [draft](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of#Specifications) but it’s been (experimentally) supported in Node since 10.0.0, released 2018-04-24.

I’m using:

* Atom 1.32.1
* language-javascript 0.129.15
* MacOS 10.13.6 (17G65)

**Comment by maxbrunsfeld** [comment]
This will be included in Atom 1.32.2, which should go out in the next few days.
