### ISSUE TITLE
statement_block should have higher precedence than object

### ISSUE THREAD

**Issue by marijnh** [tree-sitter/tree-sitter-javascript#86]
There's a test `{a, b} = object`, which I guess motivates the current precedence, but that's actually a syntax error—you (awkwardly enough) have to wrap statement-level destructuring assignments in parentheses in JavaScript, because an opening curly at statement level always starts a block.

**Comment by maxbrunsfeld** [comment]
What construct do we parse incorrectly as a result? Stuff like `() => {}`, or `() => {aLabel: aCall()}`?

**Comment by marijnh** [comment]
A block like `{}` or  `{foo: 2}` is treated as an object literal, for example.

**Comment by maxbrunsfeld** [comment]
Fixed via #104.
